name: Chocolatine
on: [push, pull_request]
env:
  MIRROR_URL: "https://github.com/EpitechPromo2026/B-DOP-200-BDX-2-1-chocolatine-adrien.ricou.git"
  EXECUTABLES: "a.out"
  branches-ignore:
      - 'ga-ignore-'
    jobs:
      to_github:
        #needs: previous_job // [previous_job, previous_job2]
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
            with:
              fetch-depth: 0
          - uses: pixta-dev/repository-mirroring-action@v1
            with:
              target_repo_url:
                ${{ MIRROR_URL }}
              ssh_private_key:
                ${{ secrets.CHOCOLATINE_SECRET }}