name: repo_size
on: [push]
jobs:
  repo-size:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: actions/checkout
          fetch-depth: 0
      - run: echo $(git branch --show-current)
      - run: du -skh --exclude=".git"